--- 
- name: juniper banner demo
  hosts: juniper
  tasks:
    - name: create a login banner
      junos_banner:
        banner: login
        text: |
          this is matts login banner
          that contains a multiline
          string to show that matt is the best
        state: present      
